# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d63af5c54fb2eb8e6c8405d72b416370f0307c2ea5c2bf6baabfb1ad00aa72c2030c0dae4262a2499e14bb34b42e686a45aae11b8d4b2001492ba7db83635c1

test:
  secret_key_base: 4f3d9824b2492005ae597726af793d5054fc486649fbf105223bba0bfd06b33495907fd6ee5d5584b7aa5b9e4f3956b91e581bb0e51515b6e56e6ca45f8034e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
